In [29]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [19]:
data=pd.read_csv("spam_detection_dataset.csv")
data

                                              Message Label
0   Congratulations! You have won a free iPhone. C...  Spam
1                           Hi, are we meeting today?   Ham
2            You have been selected for a cash prize.  Spam
3                   Don't forget our meeting at 3 PM.   Ham
4             Free entry in a lucky draw. Click here!  Spam
5                          Can you send me the notes?   Ham
6             Your loan has been approved. Apply now!  Spam
7               Happy Birthday! Have a wonderful day.   Ham
8                Win Rs.50000 by participating today.  Spam
9                 Please call me when you reach home.   Ham
10             Exclusive offer! Buy one get one free.  Spam
11                      I have sent you the document.   Ham
12  Urgent! Your account will be blocked. Verify now.  Spam
13                Let's have lunch together tomorrow.   Ham
14        You are the lucky winner of a gift voucher.  Spam
15                    Thanks for your help yesterday.   Ham
16         Limited-time offer! Claim your reward now.  Spam
17                Where are you? I'm waiting outside.   Ham
18  Congratulations! You have won a free vacation ...  Spam
19                       I'll be there in 10 minutes.   Ham

In [20]:
data.head()

                                             Message Label
0  Congratulations! You have won a free iPhone. C...  Spam
1                          Hi, are we meeting today?   Ham
2           You have been selected for a cash prize.  Spam
3                  Don't forget our meeting at 3 PM.   Ham
4            Free entry in a lucky draw. Click here!  Spam

In [21]:
print(data.isnull().sum())

Message    0
Label      0
dtype: int64

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Message  20 non-null     object
 1   Label    20 non-null     object
dtypes: object(2)
memory usage: 448.0+ bytes

In [23]:
data.shape

(20, 2)

In [24]:
data["Label"].value_counts()

Label
Spam    10
Ham     10
Name: count, dtype: int64

In [25]:
cv = CountVectorizer()

In [26]:
X = cv.fit_transform(data["Message"])

In [27]:
y = data["Label"]

In [28]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [30]:
model = MultinomialNB()

In [31]:
model.fit(X_train, y_train)

MultinomialNB()

In [33]:
prediction = model.predict(X_test)

In [34]:
prediction

array(['Spam', 'Spam', 'Spam', 'Spam'], dtype='<U4')

In [39]:
text = input("Enter Message : ")
text_vector = cv.transform([text])
prediction = model.predict(text_vector)
if prediction[0] == "Spam":
    print("Spam Message")
else:
    print("Ham  Message")

Enter Message :  congrulation you are selected

Spam Message