In [1]:
import pandas as pd
import numpy as np

In [ ]:
data=pd.read_csv

In [2]:
import matplotlib.pyplot as plt
from scipy.stats  import binom
import numpy as np
n=12
p=0.6
k=10
prob=binom.pmf(k,n,p)#shows highest possibilty is 0.06  which means 60% chance for sucess
print(prob)

0.06385228185600002

In [3]:
import matplotlib.pyplot as plt
from scipy.stats import binom
import numpy as np
n=25
p=0.6
k=15
probablity=binom.pmf(k,n,p)
print(probablity)

0.16115793869486383

In [13]:
from scipy.stats import binom
n=12
p=0.6
k=10
p=binom.cdf(n,k,p)
print(p)

1.0

In [8]:
from scipy.stats import binom
n=12
p=0.6
k=10
p=binom.cdf(k,n,p)
print(p)

0.980408958976

In [14]:
from scipy.stats import zscore
# Data values
data = [10, 20, 30, 40, 50]
# Automatic Z-score calculation
result = zscore(data)
print("Data:", data)
print("Z-scores:", result)

Data: [10, 20, 30, 40, 50]
Z-scores: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

In [17]:
from scipy.stats import zscore
data=[50,60,70,80,90]
result=zscore(data)
print(data)
print(result)

[50, 60, 70, 80, 90]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

In [20]:
data=pd.read_csv("/content/ipl_data.csv")
data

,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
0,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,1,0,0.1,1,0,0,0,222
1,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,1,0,0.2,1,0,0,0,222
2,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.2,2,0,0,0,222
3,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.3,2,0,0,0,222
4,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.4,2,0,0,0,222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76009,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,121,7,19.2,40,0,40,12,129
76010,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,127,7,19.3,46,0,46,12,129
76011,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,128,7,19.4,47,0,47,12,129
76012,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,MG Johnson,DT Christian,129,7,19.5,48,0,47,13,129
76013,617,2017-05-21,"Rajiv Gandhi International Stadium, Uppal",Mumbai Indians,Rising Pune Supergiant,KH Pandya,DT Christian,129,8,19.6,47,1,47,13,129

In [24]:
df=data["date"]
df

0        2008-04-18
1        2008-04-18
2        2008-04-18
3        2008-04-18
4        2008-04-18
            ...
76009    2017-05-21
76010    2017-05-21
76011    2017-05-21
76012    2017-05-21
76013    2017-05-21
Name: date, Length: 76014, dtype: object

In [25]:
data["bowl_team"]

0        Royal Challengers Bangalore
1        Royal Challengers Bangalore
2        Royal Challengers Bangalore
3        Royal Challengers Bangalore
4        Royal Challengers Bangalore
                    ...
76009         Rising Pune Supergiant
76010         Rising Pune Supergiant
76011         Rising Pune Supergiant
76012         Rising Pune Supergiant
76013         Rising Pune Supergiant
Name: bowl_team, Length: 76014, dtype: object

In [31]:
data=pd.read_csv("/content/StudentPerformanceFactors.csv")
data

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [32]:
x=data["Hours_Studied"]
x

0       23
1       19
2       24
3       29
4       19
        ..
6602    25
6603    23
6604    20
6605    10
6606    15
Name: Hours_Studied, Length: 6607, dtype: int64

In [34]:
y=data["Exam_Score"]
y

0       67
1       61
2       74
3       71
4       70
        ..
6602    68
6603    69
6604    68
6605    68
6606    64
Name: Exam_Score, Length: 6607, dtype: int64

In [35]:

coffecient=np.corrcoef(x,y)

In [36]:
print(coffecient)

[[1.         0.44545495]
 [0.44545495 1.        ]]

In [37]:

r=coffecient[0,1]
print("corelational cofficient is:",r)

corelational cofficient is: 0.44545495407528235

In [38]:
import math
Z = 1.96
sigma = 10
n = 100
ME = Z * (sigma / math.sqrt(n))
print("Margin of Error =", ME)

Margin of Error = 1.96

In [39]:
import math
z=1.96
sig=10
n=50
me=z*(sig/math.sqrt(n))
print(me)

2.771858582251266

In [40]:
import numpy as np
# Example dataset
hours = np.array([1, 2, 3, 4, 5])
marks = np.array([30, 40, 50, 65, 80])
# Correlation matrix
r_matrix = np.corrcoef(hours, marks)
# Extract r value
r = r_matrix[0, 1]
print("Correlation coefficient (r):", r)

Correlation coefficient (r): 0.9944466052196624

In [42]:
import numpy as np
hours=np.array([5,6,7,8,10])
marks=np.array([50,60,77,80,99])
r_matrix=np.corrcoef(hours,marks)
r=r_matrix[0,1]
print(r)

0.9854346156046278